#!/command/with-contenv bash

FLAGS=""

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTH_KEY ]; then
    echo '[!] TAILSCALE_AUTH_KEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTH_KEY}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_SSH ]; then
    FLAGS="${FLAGS} --ssh=true"
fi

echo '[i] running `tailscale up '"${FLAGS}"'`'
tailscale up $FLAGS

# configure serve
echo '[i] running `tailscale serve https:443 / http://localhost:3000`'
tailscale serve https:443 / http://localhost:3000

# configure funnel
if [ -v TAILSCALE_FUNNEL ]; then
    echo '[i] running `tailscale funnel 443 on`'
    tailscale funnel 443 on
fi