#!/command/with-contenv bash

FLAGS=""

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTH_KEY ]; then
    echo '[!] TAILSCALE_AUTH_KEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTH_KEY}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_SSH ]; then
    FLAGS="${FLAGS} --ssh=true"
fi

echo '[i] running `tailscale up '"${FLAGS}"'`'
tailscale up $FLAGS

# configure serve
echo '[i] running `tailscale serve https:443 / http://localhost:3000`'
tailscale serve https:443 / http://localhost:3000

# configure funnel
if [ -v TAILSCALE_FUNNEL ]; then
    echo '[i] running `tailscale funnel 443 on`'
    tailscale funnel 443 on
fi
if [ $TAILSCALE_FUNNEL = "true" ]; then
    echo '[!] TAILSCALE_FUNNEL is enabled!'
    echo '[i] running `tailscale funnel -bg http://localhost:3000`'
    tailscale funnel -bg http://localhost:3000
else
    echo '[!] TAILSCALE_FUNNEL is disabled!'
    echo '[i] running `http://localhost:3000`'
    tailscale serve -bg http://localhost:3000
fi

# configure auto update
if [ -v TAILSCALE_AUTO_UPDATE ]; then
    echo '[i] running `tailscale set --auto-update`'
    tailscale set --auto-update
fi